
console.log('tut30.js included');

try {
    aaaaaa991-1
} catch (error) {
    console.log(String(error.message));
    // throw new Error('baba error hai!!!!!!!!')
}finally{
    console.log("inside finally");
}
